local named_colors = require("nord.named_colors")

local syntax_colors = {
	selection_background = "#1679b6cc",
    descriptionForeground = "#61a6d1",
    errorForeground = "#e34e1c",
    widget_shadow = "#00000044",
    editor_background = "#010107",
    editor_foreground = "#becfda",
    editorLineNumber_foreground = "#4d6c80",
    editorLineNumber_activeForeground = "#61a6d1",
    editorCursor_foreground = "#EA7773",
    editor_minimap_autohide = true,
    editor_minimap_scale = 2,
    badge_background = "#49ace9",
    badge_foreground = "#0f1315",
    activityBar_background = "#07273b",
    activityBar_dropBackground = "#61a6d165",
    activityBar_border = "#0f1315",
    activityBar_foreground = "#1679b6",
    activityBar_inactiveForeground = "#1679b677",
    activityBarBadge_background = "#49ace9",
    activityBarBadge_foreground = "#0f1315",
    activityBar_activeBackground = "#49ace933",
    activityBar_activeBorder = "#49ace9",
    sideBar_background = "#010305",
    sideBar_dropBackground = "#062132",
    sideBar_border = "#515151",
    sideBar_foreground = "#9fb6c6",
    sideBarSectionHeader_background = "#09334e",
    sideBarSectionHeader_foreground = "#9fb6c6",
    sideBarTitle_foreground = "#9fb6c6",
    sideBarSectionHeader_border = "#0f1315",
    statusBar_foreground = "#1679b6",
    statusBar_background = "#07273b",
    statusBar_border = "#0f1315",
    statusBar_debuggingBackground = "#07273b",
    statusBar_debuggingForeground = "#ff80ac50",
    statusBar_debuggingBorder = "#ff80acaf",
    statusBar_noFolderForeground = "#879dab",
    statusBar_noFolderBackground = "#07273b",
    statusBar_noFolderBorder = "#07273b",
    statusBarItem_activeBackground = "#007ecc59",
    statusBarItem_hoverBackground = "#0a3652",
    statusBarItem_prominentBackground = "#051e2e",
    statusBarItem_prominentHoverBackground = "#002f4d",
    button_background = "#007f99",
    button_foreground = "#ebf7ff",
    button_hoverBackground = "#0ac",
    dropdown_background = "#09334e",
    dropdown_border = "#09334e",
    dropdown_foreground = "#61a6d1",
    editorMarkerNavigation_background = "#3a3a5e29",
    editorMarkerNavigationError_background = "#e34e1c",
    editorMarkerNavigationWarning_background = "#e69533",
    editorError_border = "#07273b",
    editorError_foreground = "#e34e1c",
    editorWarning_border = "#07273b",
    editorWarning_foreground = "#e69533",
    editorInfo_border = "#07273b",
    editor_foldBackground = "#0A1724",
    editorInfo_foreground = "#49ace9",
    editorHint_border = "#49e9a600",
    editorHint_foreground = "#49e9a6",
    editorGroup_emptyBackground = "#4d6c8033",
    editorGroup_border = "#0f1315",
    editorGroup_dropBackground = "#4d6c8033",
    editorGroupHeader_noTabsBackground = "#09334e",
    editorGroupHeader_tabsBackground = "#09334e",
    editorGroupHeader_tabsBorder = "#09334e",
    tab_activeBackground = "#000000",
    tab_unfocusedActiveBackground = "#002c47",
    tab_activeForeground = "#FFFFFF",
    tab_border = "#0f1315",
    tab_inactiveBackground = "#09334e",
    tab_inactiveForeground = "#9fb6c6",
    tab_unfocusedActiveForeground = "#9fb6c6",
    tab_unfocusedInactiveForeground = "#9fb6c6",
    tab_activeBorderTop = "#FFFFFF",
    tab_activeModifiedBorder = "#49e9a6",
    tab_activeBorder = "#FFFFFF",
    tab_unfocusedActiveBorder = "#07273b",
    tab_unfocusedHoverBackground = "#1679b621",
    textBlockQuote_background = "#07273b",
    textBlockQuote_border = "#1679b6",
    textCodeBlock_background = "#07273b",
    textLink_activeForeground = "#49ace9",
    textLink_foreground = "#49ace9",
    textPreformat_foreground = "#ffc180",
    textSeparator_foreground = "#07273b",
    walkThrough_embeddedEditorBackground = "#07273b",
    welcomePage_buttonBackground = "#051b29",
    welcomePage_buttonHoverBackground = "#09334e",
    input_background = "#051b29",
    input_border = "#002f4d",
    input_foreground = "#CDD3DE",
    input_placeholderForeground = "#879dab",
    inputOption_activeBorder = "#1679b6",
    inputValidation_errorForeground = "#ff4000",
    inputValidation_errorBackground = "#501502ee",
    inputValidation_errorBorder = "#691c02",
    inputValidation_infoForeground = "#40d4e7",
    inputValidation_infoBackground = "#0f6e7bee",
    inputValidation_infoBorder = "#148f9f",
    inputValidation_warningForeground = "#e69533",
    inputValidation_warningBackground = "#82694acc",
    inputValidation_warningBorder = "#a88457",
    editorWidget_background = "#09334e",
    editorWidget_border = "#0f1315",
    editorHoverWidget_background = "#002942",
    editorHoverWidget_border = "#0f1315",
    editorSuggestWidget_background = "#002942",
    editorSuggestWidget_border = "#0f1315",
    editorSuggestWidget_foreground = "#9fb6c6",
    editorSuggestWidget_highlightForeground = "#49ace9",
    editorSuggestWidget_selectedBackground = "#0c3f5f",
    editorGutter_background = "#010107",
    editorGutter_addedBackground = "#8ce99a",
    editorGutter_deletedBackground = "#e34e1c",
    editorGutter_modifiedBackground = "#ffc180",
    editor_selectionBackground = "#1679b6BF",
    editor_selectionHighlightBackground = "#49ace933",
    editor_inactiveSelectionBackground = "#1679b633",
    editor_wordHighlightStrongBackground = "#cc990033",
    editor_wordHighlightBackground = "#e4b78133",
    editor_findMatchBackground = "#40bf6a11",
    editor_findMatchHighlightBackground = "#0e667179",
    editor_findRangeHighlightBackground = "#49e9a622",
    editor_hoverHighlightBackground = "#1679b63f",
    editor_lineHighlightBackground = "#003c61ee",
    editor_lineHighlightBorder = "#003c61",
    editor_rangeHighlightBackground = "#49d6e922",
    editorLink_activeForeground = "#14a5ff",
    editorWhitespace_foreground = "#ffffff21",
    editorIndentGuide_background = "#183c53",
    editorIndentGuide_activeBackground = "#28658a",
    editorBracketMatch_background = "#1679b622",
    editorBracketMatch_border = "#1679b6",
    editorRuler_foreground = "#1a425b",
    editorCodeLens_foreground = "#5b858b",
    terminal_ansiBlack = "#28353e",
    terminal_ansiRed = "#e66533",
    terminal_ansiGreen = "#49e9a6",
    terminal_ansiYellow = "#e4b781",
    terminal_ansiBlue = "#49ace9",
    terminal_ansiMagenta = "#df769b",
    terminal_ansiCyan = "#49d6e9",
    terminal_ansiWhite = "#aec3d0",
    terminal_ansiBrightBlack = "#475e6c",
    terminal_ansiBrightRed = "#e97749",
    terminal_ansiBrightGreen = "#60ebb1",
    terminal_ansiBrightYellow = "#e69533",
    terminal_ansiBrightBlue = "#60b6eb",
    terminal_ansiBrightMagenta = "#e798b3",
    terminal_ansiBrightCyan = "#60dbeb",
    terminal_ansiBrightWhite = "#becfda",
    terminal_foreground = "#becfda",
    terminalCursor_background = "#051b29",
    terminalCursor_foreground = "#becfda",
    terminal_background = "#070707",
    terminal_selectionBackground = "#E07C24",
    terminal_selectionForeground = "#000000",
    merge_border = "#07273b00",
    merge_currentContentBackground = "#85f1ff22",
    merge_currentHeaderBackground = "#85f1ff44",
    merge_incomingContentBackground = "#9d92f222",
    merge_incomingHeaderBackground = "#9d92f244",
    merge_commonContentBackground = "#ffc18022",
    merge_commonHeaderBackground = "#ffc18044",
    editorOverviewRuler_currentContentForeground = "#85f1ff44",
    editorOverviewRuler_incomingContentForeground = "#9d92f244",
    editorOverviewRuler_commonContentForeground = "#ffc18044",
    editorOverviewRuler_border = "#07273b",
    notificationCenter_border = "#09334e",
    notificationCenterHeader_foreground = "#879dab",
    notificationCenterHeader_background = "#09334e",
    notificationToast_border = "#09334e",
    notifications_foreground = "#CDD3DE",
    notifications_background = "#09334e",
    notifications_border = "#09334e",
    notificationLink_foreground = "#879dab",
    diffEditor_insertedTextBackground = "#16b67327",
    diffEditor_removedTextBackground = "#e6653341",
    debugToolBar_background = "#07273b",
    debugExceptionWidget_background = "#07273b",
    debugExceptionWidget_border = "#1679b6",
    extensionButton_prominentBackground = "#008c99",
    extensionButton_prominentForeground = "#e5f5f5",
    extensionButton_prominentHoverBackground = "#00bbcc",
    focusBorder = "#09334e",
    foreground = "#becfda",
    panel_background = "#051b29",
    panel_border = "#1679b6",
    panelTitle_activeBorder = "#1679b6",
    panelTitle_activeForeground = "#49ace9",
    panelTitle_inactiveForeground = "#507b95",
    peekView_border = "#1679b6",
    peekViewEditor_background = "#001f33",
    peekViewEditor_matchHighlightBackground = "#005b9433",
    peekViewEditor_matchHighlightBorder = "#007ecc",
    peekViewEditorGutter_background = "#001f33",
    peekViewResult_background = "#002338",
    peekViewResult_fileForeground = "#ffc180",
    peekViewResult_lineForeground = "#879dab",
    peekViewResult_matchHighlightBackground = "#09334e",
    peekViewResult_selectionBackground = "#09334e",
    peekViewResult_selectionForeground = "#879dab",
    peekViewTitle_background = "#002338",
    peekViewTitleDescription_foreground = "#879dab",
    peekViewTitleLabel_foreground = "#ffc180",
    progressBar_background = "#49ace9",
    scrollbar_shadow = "#00000044",
    scrollbarSlider_activeBackground = "#008ee677",
    scrollbarSlider_background = "#008ee633",
    scrollbarSlider_hoverBackground = "#008ee655",
    gitDecoration_addedResourceForeground = "#16b673",
    gitDecoration_modifiedResourceForeground = "#49e9a6",
    gitDecoration_deletedResourceForeground = "#e34e1c",
    gitDecoration_untrackedResourceForeground = "#40d4e7",
    gitDecoration_ignoredResourceForeground = "#5b788b",
    gitDecoration_conflictingResourceForeground = "#ffc180",
    pickerGroup_border = "#1679b6",
    pickerGroup_foreground = "#49ace9",
    list_activeSelectionBackground = "#0c3f5f",
    list_activeSelectionForeground = "#ebf7ff",
    list_dropBackground = "#002a4d",
    list_focusBackground = "#0b3c5b",
    list_focusForeground = "#ebf7ff",
    list_highlightForeground = "#49ace9",
    list_hoverBackground = "#00558a65",
    list_hoverForeground = "#ebf7ff",
    list_inactiveFocusBackground = "#082d44",
    list_inactiveSelectionBackground = "#09334e",
    list_inactiveSelectionForeground = "#becfda",
    list_errorForeground = "#e34e1c",
    list_warningForeground = "#ffa857",
    listFilterWidget_background = "#002a4d",
    listFilterWidget_outline = "#49e9a6",
    listFilterWidget_noMatchesOutline = "#e34e1c",
    tree_indentGuidesStroke = "#f6f6f6",
    tree_indent = 15,
    tree_renderIndentGuides = "always",
    settings_headerForeground = "#becfda",
    settings_modifiedItemIndicator = "#15ac31",
    settings_dropdownListBorder = "#0051a877",
    settings_dropdownBackground = "#09334e",
    settings_dropdownForeground = "#0ac",
    settings_dropdownBorder = "#09334e",
    settings_checkboxBackground = "#09334e",
    settings_checkboxForeground = "#0ac",
    settings_checkboxBorder = "#09334e",
    settings_textInputBackground = "#09334e",
    settings_textInputForeground = "#0ac",
    settings_textInputBorder = "#09334e",
    settings_numberInputBackground = "#051b29",
    settings_numberInputForeground = "#7060eb",
    settings_numberInputBorder = "#051b29",
    breadcrumb_foreground = "#9fb6c6",
    breadcrumb_background = "#07273b",
    breadcrumb_focusForeground = "#49ace9",
    breadcrumb_activeSelectionForeground = "#ebf7ff",
    breadcrumbPicker_background = "#09334e",
    titleBar_activeBackground = "#07273b",
    titleBar_activeForeground = "#becfda",
    titleBar_inactiveBackground = "#07273b",
    titleBar_inactiveForeground = "#9fb6c6",
    menu_background = "#09334e",
    menu_foreground = "#9fb6c6",
    menu_selectionBackground = "#0b3c5b",
    menu_selectionForeground = "#49ace9",
    menu_selectionBorder = "#0b3c5b",
    menu_separatorBackground = "#49ace9",
    menubar_selectionBackground = "#0b3c5b",
    menubar_selectionForeground = "#49ace9",
    menubar_selectionBorder = "#0b3c5b",
    editor_snippetTabstopHighlightBackground = "#051b29",
    editor_snippetTabstopHighlightBorder = "#062132",
    editor_snippetFinalTabstopHighlightBackground = "#051b29",
    editor_snippetFinalTabstopHighlightBorder = "#062132",
    minimap_findMatchHighlight = "#49ace9ee",
    minimap_errorHighlight = "#e34e1cee",
    minimap_warningHighlight = "#e69533ee",
    minimapGutter_addedBackground = "#16b673",
    minimapGutter_modifiedBackground = "#49e9a6",
    minimapGutter_deletedBackground = "#e34e1c",
    minimap_background = "#07273b99",
	comment_fg = "#dcdcdc",
	text_fg = "#becfda",
	keyword_fg = "#df769b",
	variable_fg = "#e4b781",
	annotation_fg = "#d67e5c",
	constant_fg = "#d5971a",
	tag_fg = "#e66533",
	string_fg = "#49e9a6",
	string_interpolated_fg = "#16b673",
	number_fg = "#7060eb",
	function_fg = "#16a3b6",
	support_fg = "#49d6e9",
	misc_fg = "#49ace9",
	invalid_fg = "#e3541c",

}

local dark_colors = {
	nord0_gui = named_colors.black, -- nord0 in palette
	nord1_gui = named_colors.dark_gray, -- nord1 in palette
	nord2_gui = named_colors.gray, -- nord2 in palette
	nord3_gui = named_colors.light_gray, -- nord3 in palette
	nord3_gui_bright = named_colors.light_gray_bright, -- out of palette
	nord4_gui = named_colors.darkest_white, -- nord4 in palette
	nord5_gui = named_colors.darker_white, -- nord5 in palette
	nord6_gui = named_colors.white, -- nord6 in palette
	nord7_gui = named_colors.teal, -- nord7 in palette
	nord8_gui = named_colors.off_blue, -- nord8 in palette
	nord9_gui = named_colors.glacier, -- nord9 in palette
	nord10_gui = named_colors.blue, -- nord10 in palette
	nord11_gui = named_colors.red, -- nord11 in palette
	nord12_gui = named_colors.orange, -- nord12 in palette
	nord13_gui = named_colors.yellow, -- nord13 in palette
	nord14_gui = named_colors.green, -- nord14 in palette
	nord15_gui = named_colors.purple, -- nord15 in palette
	none = "NONE",
}

local light_colors = {
	nord0_gui = named_colors.white, -- nord0 in palette
	nord1_gui = named_colors.darker_white, -- nord1 in palette
	nord2_gui = named_colors.darkest_white, -- nord2 in palette
	nord3_gui = named_colors.light_gray, -- nord3 in palette
	nord3_gui_bright = named_colors.light_gray_bright, -- out of palette
	nord4_gui = named_colors.gray, -- nord4 in palette
	nord5_gui = named_colors.dark_gray, -- nord5 in palette
	nord6_gui = named_colors.black, -- nord6 in palette

	-- Same colors across light and dark from here down...
	nord7_gui = named_colors.teal, -- nord7 in palette
	nord8_gui = named_colors.off_blue, -- nord8 in palette
	nord9_gui = named_colors.glacier, -- nord9 in palette
	nord10_gui = named_colors.blue, -- nord10 in palette
	nord11_gui = named_colors.red, -- nord11 in palette
	nord12_gui = named_colors.orange, -- nord12 in palette
	nord13_gui = named_colors.yellow, -- nord13 in palette
	nord14_gui = named_colors.green, -- nord14 in palette
	nord15_gui = named_colors.purple, -- nord15 in palette
	none = "NONE",
}

local default = (vim.o.background == "dark") and dark_colors or light_colors

function merge(t1, t2)
    for k, v in pairs(t2) do
        t1[k] = v
    end
    return t1
end

local nord = merge(default, syntax_colors)

-- Enable contrast sidebars, floating windows and popup menus
if vim.g.nord_contrast then
	nord.sidebar = nord.nord1_gui
	nord.float = nord.nord1_gui
else
	nord.sidebar = nord.nord0_gui
	nord.float = nord.nord0_gui
end

if vim.g.nord_cursorline_transparent then
	nord.cursorlinefg = nord.nord0_gui
else
	nord.cursorlinefg = nord.nord1_gui
end

return nord
